version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:9
    steps:
      - checkout
      - run: curl -O https://download.clojure.org/install/linux-install-1.9.0.375.sh
      - run: chmod +x linux-install-1.9.0.375.sh
      - run: ./linux-install-1.9.0.375.sh --prefix `pwd`
      - run: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - run: sudo apt-get install -y nodejs
      - run: bin/clojure -A:test && bin/clojure -A:test-cljs
